apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo-task-api
spec:
  selector:
    matchLabels:
      app: neo-task-api
  template:
    metadata:
      labels:
        app: neo-task-api
    spec:
      containers:
      - name: neo-task-api
        image: tanyongang/neo-task-api:2.0.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_VHOST
          value: "/"
        
---
apiVersion: v1
kind: Service
metadata:
  name: neo-task-api
spec:
  type: NodePort
  selector:
    app: neo-task-api
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31500